apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking-platform
type: Opaque
stringData:
  sql-connection: "Server=sqlserver;Database=BankingAuth;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;"
  jwt-secret-key: "CHANGE_ME_TO_SECURE_KEY"
  mongodb-connection: "mongodb://user:password@mongodb:27017/banking_documents?authSource=admin"
  kafka-bootstrap-servers: "kafka:29092"
  redis-connection: "redis:6379"


